export const ghanaRegions: Record<string, string[]> = {
  "Greater Accra": [
    "Accra",
    "Tema",
    "Madina",
    "Adenta",
    "Teshie",
    "Nungua",
    "Ashaiman",
    "Dome",
    "Achimota",
    "Dansoman",
    "Lapaz",
    "Osu",
    "Kaneshie",
    "Labadi",
    "East Legon",
    "Spintex",
    "Kasoa",
  ],
  Ashanti: [
    "Kumasi",
    "Obuasi",
    "Ejisu",
    "Bekwai",
    "Mampong",
    "Konongo",
    "Offinso",
    "Asokwa",
    "Tafo",
    "Suame",
    "Bantama",
    "Asante Akim",
    "Ejura",
    "Juaben",
    "Agona",
  ],
  Western: [
    "Sekondi-Takoradi",
    "Tarkwa",
    "Axim",
    "Nkroful",
    "Agona Nkwanta",
    "Bogoso",
    "Prestea",
    "Wassa Akropong",
    "Daboase",
    "Shama",
    "Dixcove",
    "Half Assini",
  ],
  Eastern: [
    "Koforidua",
    "Nkawkaw",
    "Nsawam",
    "Suhum",
    "Akosombo",
    "Somanya",
    "Aburi",
    "Akim Oda",
    "Akropong",
    "Begoro",
    "Kade",
    "Mpraeso",
    "Kibi",
  ],
  Central: [
    "Cape Coast",
    "Winneba",
    "Mankessim",
    "Elmina",
    "Kasoa",
    "Swedru",
    "Apam",
    "Saltpond",
    "Assin Fosu",
    "Dunkwa-on-Offin",
    "Twifo Praso",
    "Budumburam",
  ],
  Volta: [
    "Ho",
    "Keta",
    "Hohoe",
    "Kpando",
    "Anloga",
    "Aflao",
    "Dzodze",
    "Akatsi",
    "Kpeve",
    "Adidome",
    "Peki",
    "Denu",
    "Sogakope",
  ],
  Northern: [
    "Tamale",
    "Yendi",
    "Savelugu",
    "Bimbilla",
    "Gushegu",
    "Karaga",
    "Kpandai",
    "Wulensi",
    "Zabzugu",
    "Nalerigu",
    "Walewale",
    "Gambaga",
  ],
  "Upper East": ["Bolgatanga", "Navrongo", "Bawku", "Zebilla", "Tongo", "Paga", "Sandema", "Garu", "Pusiga", "Tempane"],
  "Upper West": ["Wa", "Lawra", "Jirapa", "Nandom", "Tumu", "Lambussie", "Nadowli", "Kaleo", "Wechiau", "Gwollu"],
  Bono: [
    "Sunyani",
    "Berekum",
    "Dormaa Ahenkro",
    "Nsoatre",
    "Wamfie",
    "Sampa",
    "Odumase",
    "Wenchi",
    "Techiman",
    "Kintampo",
  ],
  "Bono East": [
    "Techiman",
    "Kintampo",
    "Nkoranza",
    "Atebubu",
    "Yeji",
    "Prang",
    "Kwame Danso",
    "Jema",
    "Kajaji",
    "Buoyem",
  ],
  Ahafo: [
    "Goaso",
    "Hwidiem",
    "Kenyasi",
    "Kukuom",
    "Sankore",
    "Bechem",
    "Duayaw Nkwanta",
    "Mim",
    "Acherensua",
    "Ntotroso",
  ],
  Savannah: ["Damongo", "Salaga", "Bole", "Sawla", "Buipe", "Daboya", "Bamboi", "Mpaha", "Larabanga", "Busunu"],
  "North East": [
    "Nalerigu",
    "Walewale",
    "Gambaga",
    "Chereponi",
    "Bunkpurugu",
    "Yunyoo",
    "Wungu",
    "Langbinsi",
    "Gbintiri",
    "Nakpanduri",
  ],
  Oti: [
    "Dambai",
    "Jasikan",
    "Kadjebi",
    "Nkwanta",
    "Kete Krachi",
    "Chinderi",
    "Worawora",
    "Brewaniase",
    "Kwamekrom",
    "Banda",
  ],
  "Western North": [
    "Sefwi Wiawso",
    "Bibiani",
    "Enchi",
    "Juaboso",
    "Akontombra",
    "Dadieso",
    "Bodi",
    "Asawinso",
    "Adabokrom",
    "Essam",
  ],
}
