export const popularBrands = {
  
  electronics: [
    "Apple",
    "Samsung",
    "Sony",
    "LG",
    "Dell",
    "HP",
    "Lenovo",
    "Asus",
    "Acer",
    "Panasonic",
    "Philips",
    "Bose",
    "JBL",
    "Xiaomi",
    "OnePlus"
  ],
  fashion: [
    "Nike",
    "Adidas",
    "Zara",
    "H&M",
    "Gucci",
    "Louis Vuitton",
    "Uniqlo",
    "Chanel",
    "Prada",
    "Under Armour",
    "Puma",
    "Balenciaga",
    "Levi's",
    "Forever 21",
    "Burberry"
  ],
  furniture: [
    "IKEA",
    "Ashley Furniture",
    "Wayfair",
    "La-Z-Boy",
    "West Elm",
    "Herman Miller",
    "Restoration Hardware",
    "Crate & Barrel",
    "CB2",
    "Pottery Barn",
    "Flexsteel",
    "Bassett",
    "Raymour & Flanigan",
    "Urban Ladder",
    "Article"
  ]
}

export const brandsByCategory: Record<string, string[]> = {
  electronics: [
    "Samsung",
    "Apple",
    "Sony",
    "LG",
    "Huawei",
    "Tecno",
    "Infinix",
    "Nokia",
    "HP",
    "Dell",
    "Lenovo",
    "Asus",
    "Other",
  ],
  vehicles: [
    "Toyota",
    "Honda",
    "Hyundai",
    "Kia",
    "Nissan",
    "Ford",
    "Chevrolet",
    "Mercedes-Benz",
    "BMW",
    "Volkswagen",
    "Mazda",
    "Mitsubishi",
    "Other",
  ],
  clothing: [
    "Nike",
    "Adidas",
    "Puma",
    "Zara",
    "H&M",
    "Gucci",
    "Louis Vuitton",
    "Versace",
    "Tommy Hilfiger",
    "Calvin Klein",
    "Other",
  ],
  furniture: ["IKEA", "Ashley Furniture", "Woodin", "La-Z-Boy", "Ashanti Design", "Moda Furnishings", "Other"],
  gaming : [
    "Sony",
    "Microsoft",
    "Nintendo",
    "Razer",
    "Alienware",
    "Asus ROG",
    "MSI",
    "Acer Predator",
    "Logitech G",
    "Corsair",
    "SteelSeries",
    "HyperX",
    "AMD",
    "NVIDIA",
    "Intel",
    "Turtle Beach",
    "Elgato",
    "PowerA",
    "Thrustmaster",
    "Cooler Master",
    "Other"
  ],
  default: ["Generic", "Local Brand", "Imported", "Handmade", "Custom", "Other"],
}